// flow-typed signature: ce4134b0dec84fd45c8e8b631aa6d642
// flow-typed version: <<STUB>>/react-logger_v^1.1.0/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-logger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-logger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-logger/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-logger/index' {
  declare module.exports: $Exports<'react-logger'>;
}
declare module 'react-logger/index.js' {
  declare module.exports: $Exports<'react-logger'>;
}
declare module 'react-logger/test/index.js' {
  declare module.exports: $Exports<'react-logger/test/index'>;
}
